#!/usr/bin/env python3
"""
LQIP generator — blur-up placeholders for snappy image loading.

For every gallery image (and the avatar) this rasterises a *tiny* blurred
preview (~24px wide) and inlines it as a base64 JPEG data URI. The site shows
that placeholder instantly (cheap, ships in the HTML/JS) while the full image
lazy-loads and fades in over it.

Sources may be SVG (rasterised via `rsvg-convert`) or raster (via Pillow).
Writes: src/data/lqip.ts  ->  export const LQIP: Record<string,string>

Run from repo root:  python3 tools/gen-lqip.py
"""
import os, re, io, base64, subprocess, shutil
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUB  = os.path.join(ROOT, "public")
LQIP_W = 24          # tiny preview width
QUALITY = 40

def media_base():
    txt = open(os.path.join(ROOT, "src/config.ts")).read()
    m = re.search(r"MEDIA_BASE\s*=\s*'([^']+)'", txt)
    return m.group(1) if m else ""

def sources():
    """Yield (runtime_key, local_file) pairs to make LQIPs for.

    Gallery originals live in media-src/ (gitignored) and are served from R2 at
    MEDIA_BASE/<file>; the runtime `src` is that URL, so the LQIP must be keyed
    by it. The avatar is a normal /public asset.
    """
    base = media_base()
    txt = open(os.path.join(ROOT, "src/data/gallery.ts")).read()
    for f in re.findall(r"file:\s*'([^']+)'", txt):
        yield f"{base}/{f}", os.path.join(ROOT, "media-src", f)
    # avatar (small, lives in /public)
    yield "/profile.jpg", os.path.join(PUB, "profile.jpg")

def load_raster(path):
    """Return a PIL RGBA image for a local file (svg via rsvg, else Pillow)."""
    if not os.path.exists(path):
        return None
    if path.lower().endswith(".svg"):
        if not shutil.which("rsvg-convert"):
            return None
        png = subprocess.run(
            ["rsvg-convert", "-w", "64", path], capture_output=True, check=True
        ).stdout
        return Image.open(io.BytesIO(png)).convert("RGBA")
    return Image.open(path).convert("RGBA")

def lqip(path):
    im = load_raster(path)
    if im is None:
        return None
    w, h = im.size
    th = max(1, round(LQIP_W * h / w))
    im = im.resize((LQIP_W, th), Image.LANCZOS).filter(ImageFilter.GaussianBlur(1.1))
    # flatten onto the site's deep bg so transparent areas aren't black
    bg = Image.new("RGB", im.size, (11, 16, 32))
    bg.paste(im, mask=im.split()[-1])
    buf = io.BytesIO()
    bg.save(buf, format="JPEG", quality=QUALITY, optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode()
    return "data:image/jpeg;base64," + b64

def main():
    out = {}
    for key, path in sources():
        d = lqip(path)
        label = key.rsplit("/", 1)[-1]
        if d:
            out[key] = d
            print(f"  {label:24} -> {len(d)} bytes")
        else:
            print(f"  {label:24} -> (skipped, missing {path})")
    lines = ["// AUTO-GENERATED by tools/gen-lqip.py — do not edit by hand.",
             "// Tiny blurred base64 previews shown instantly under the lazy-loaded full image.",
             "export const LQIP: Record<string, string> = {"]
    for k, v in out.items():
        lines.append(f"  {k!r}: {v!r},")
    lines.append("};")
    lines.append("export const lqipFor = (src: string): string | undefined => LQIP[src];")
    open(os.path.join(ROOT, "src/data/lqip.ts"), "w").write("\n".join(lines) + "\n")
    print(f"wrote src/data/lqip.ts ({len(out)} entries)")

if __name__ == "__main__":
    main()
